### ISSUE TITLE
Unable to generate schema 

### ISSUE THREAD

**Issue by charanjit-singh** [HackSoftware/Django-Styleguide#68]
```
(venv) ╭─charanjit@22G /mnt/Workstation/Crove.app/backend/crove ‹develop› 
╰─$ python manage.py generateschema                                                                                       1 ↵
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/rest_framework/management/commands/generateschema.py", line 41, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/mnt/Workstation/Crove.app/backend/crove/venv/lib/python3.6/site-packages/rest_framework/schemas/openapi.py", line 81, in get_schema
    operation = view.schema.get_operation(path, method)
AttributeError: 'AutoSchema' object has no attribute 'get_operation'
```

**Comment by charanjit-singh** [comment]
![image](https://user-images.githubusercontent.com/23359602/104888305-9122b400-5992-11eb-8dd4-7a79b75dbe27.png)

Unable to get the required function.
Is it DRF issue or we're missing something in `APIDocsMixin`?

**Comment by RadoRado** [comment]
@charanjit-singh Sorry for the late answer.

We did struggle a bit with automatic schema generation & ended up with manually writing schema after that.

I'll close that for now & add a new issue to revisit the entire "Swagger from API" generation approach.
